### ISSUE TITLE
BTT Octopus Pro v1.0 F429 motor driver 3 not working

### ISSUE THREAD

**Issue by sabagmn** [TeamGloomy/TeamGloomy.github.io#17]
Not sure if this is user error or not, but here it goes:
With this motor assignment, it was not possible to get E0 working:
X driver 0
Y driver 1
Z driver 2
E0 driver 3
When trying to extrude, I get the error that phase A and/or phase B of the motor isn't connected (and yes, I am in the right connector for driver 3, not in 2.2)
The only way to get it working was to move to driver 4, where with the otherwise exact same setup, everything works as it should.
So either I have a physically non-working driver 3 output, or there is an issue in the software.

**Comment by jaysuk** [comment]
checked the pins defined in the firmware compared to the pinout and they are correct so it must be an issue with you board.
