### ISSUE TITLE
About SBC.

### ISSUE THREAD

**Issue by billhu1996** [TeamGloomy/TeamGloomy.github.io#2]
Duet3D says DSF support Raspberry Pi 2 or newer(armv7). Our wiki is 3 or newer. So is our wiki wrong?

https://github.com/Duet3D/DuetSoftwareFramework/blame/master/README.md#L5

https://github.com/TeamGloomy/TeamGloomy.github.io/blame/a1200b852c54f6d3adf3c23f3722b734c29e59bd/pages/mydoc/stm32_sbc.md#L14

https://github.com/TeamGloomy/TeamGloomy.github.io/blame/a1200b852c54f6d3adf3c23f3722b734c29e59bd/pages/mydoc/lpc_sbc.md#L14

**Comment by jaysuk** [comment]
it would technically work, see here
https://forum.duet3d.com/topic/15737/new-duet-3-setup-with-raspberry-pi-2
but the duet team recommend a pi 3B or 4
https://duet3d.dozuki.com/Wiki/Getting_Started_With_Duet_3#Section_Minimum_configuration_with_Raspberry_Pi
so we stick with that for ease.
plus the fact the 2 doesn't have wifi etc.

Thanks,

Jay

**Comment by billhu1996** [comment]
Thanks for your reply.

Now I understand.

Thanks again.

Bill
