### ISSUE TITLE
Wrong information about SPI channel to 12864 reprap discount display

### ISSUE THREAD

**Issue by Zannys** [TeamGloomy/TeamGloomy.github.io#21]
I encounter some wrong information about configure the 12864 display with ST7920 drive, on the page informs to use SPI Channel 0 to drive the display, but this doesn't work, the right one is SPI Channel 3, Spi Channel 0 is only to SD card on the display reader

**Comment by jaysuk** [comment]
which board was this again?

**Comment by Zannys** [comment]
> which board was this again?

Sorry, Fly Cdy v3

**Comment by jaysuk** [comment]
wiki has been updated, thanks
