### ISSUE TITLE
How do I get in touch with someone? I have product question.

### ISSUE THREAD

**Issue by royalfifty8** [TeamGloomy/TeamGloomy.github.io#26]
Not sure if this is the right place so forgive me if it is. Having trouble navigating through your selection of boards. My printer is Ender-3 Pro I'm looking for something that has these capabilities.

- Dual Z independent motor drivers for auto Z alignment 
- Dual extrusion.
- ability to connect Pi board e.g., Pi lite V2.0 or klipper pad 7 for WiFi connection
- 2209 drivers
- 500 degree hotend
- can bus 
- high voltage input
Thanks in advance!

**Comment by jaysuk** [comment]
We don't support klipper so this isn't the right place for you

**Comment by royalfifty8** [comment]
But its all over your store, and there's sections dedicated for klipper configs for CANbus boards on the Mellow's gihub. You sure we're talking about the same Klipper there Sunshine? lol

**Comment by jaysuk** [comment]
we are an independent group, not a manufacturer, and concentrate purely on reprapfirmware. we do not have a store. Maybe you are confusing us with Mellow? in which case use their discord https://discord.gg/4QRyWrb7T8

**Comment by royalfifty8** [comment]
Well there it is. That would be it. I thought you were Mellow because I clicked a link to that said it was for Mellows website which led me here. My sincere apology. Thank you for the clarification and actual link to Mellow.
