### ISSUE TITLE
RRF 3.5.0 wrong config in documentation

### ISSUE THREAD

**Issue by velkhor** [TeamGloomy/TeamGloomy.github.io#27]
Default configuration for spi  from
https://teamgloomy.github.io/btt_octopus_pro_1.0_f429_connected_sbc_3_5.html
```
SPI0.pins={A.5,A.6,A.7}
SPI1.pins={B.13,C.2,C.3}
SPI2.pins={B.3,B.4,B.5}
SPI3.pins={NoPin,NoPin,NoPin}
SPI4.pins={E.8,E.9,E.7}
SPI5.pins={E.12,NoPin,E.9}
```

In connecting accelometer information
wiring:
https://teamgloomy.github.io/btt_octopus_pro_1.0_f429_accelerometer_3_5.html
```
SDA - PE_7
SCL - PE_8
SDO - PE_9
```

and in Boart.txt Changes
`accelerometer.spiChannel = 5`

should be
`accelerometer.spiChannel = 4`
because PE7, PE8, PE7 are assigned to spi 4 not spi 5

**Comment by jaysuk** [comment]
thanks, updated
